# Generated by Django 5.0.4 on 2024-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='courses',
            field=models.ManyToManyField(to='lessons.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='lessons.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='purchases',
            field=models.ManyToManyField(to='account.purchase'),
        ),
    ]
