# Generated by Django 5.0.4 on 2024-05-03 13:25

import django.db.models.deletion
import lessons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=99999999)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=99999999)),
                ('text', models.CharField(max_length=99999999)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=99999999)),
                ('iconpath', models.ImageField(upload_to=lessons.models.icondir)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=99999999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.material')),
                ('chat', models.ManyToManyField(to='lessons.message')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=99999999)),
                ('accuracy', models.IntegerField(default=0)),
                ('choices', models.ManyToManyField(to='lessons.choice')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Безымянный', max_length=99999999)),
                ('price', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('lessons', models.ManyToManyField(to='lessons.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(to='lessons.choice')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(to='lessons.task'),
        ),
    ]
