# Generated by Django 5.0.4 on 2024-05-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='progress',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chat',
            field=models.ManyToManyField(null=True, to='lessons.message'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.material'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(null=True, to='lessons.task'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
