# Generated by Django 5.0.4 on 2024-05-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_course_progress_alter_lesson_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='chat',
            field=models.ManyToManyField(blank=True, to='lessons.message'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.material'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='lessons.task'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
